### PR TITLE
https-proxy-agent

### PR DESCRIPTION
**Pull request by gre**
This is an attempt to fix https://github.com/LedgerHQ/ledger-live-desktop/issues/1073
**unfortunately I can't test it because I don't reproduce any issue on Ledger Live + proxy** (tried Tor, tried Proxyman, everything works for me on Mac)

### CODE REVIEW

**Comment by G-Ray** [comment]
@gre @juan-cortes I think I got a SOCKS proxy working with my changes: https://github.com/G-Ray/ledger-live-common/commits/socks-proxy
IIUC we need to create a proxy instance both in `network.js` and `socket.js` to support ws connections.

You can test using the `SOCKS_PROXY` env:
- with `SOCKS_PROXY=[non existing proxy]`, connections should fail. (except the connections initated from the electron window I guess).
- With `SOCKS_PROXY=socks5://127.0.0.1:9150` while running Tor Browser, all ledger-live features should work hopefully.

Feel free to cherry-pick my commit. I would also be glad to open a PR with any requested changes.
More changes, and a lot of tests should be made to be sure we can support other kind of proxies.

**Comment by juan-cortes** [comment]
@G-Ray thank you!, I will take a look later today/tomorrow and get back to you

**Comment by G-Ray** [comment]
@juan-cortes Have you had time to take a look at my changes ? Thanks !

**Comment by juan-cortes** [comment]
> @juan-cortes Have you had time to take a look at my changes ? Thanks !

I'm ashamed to admit I have not been able to test yet, sorry, but I'm setting up today to do so. I did look at the changes and they seem OK for me. I'll update here once I can test.

**Comment by juan-cortes** [comment]
Addressed on https://github.com/LedgerHQ/ledger-live-common/pull/1100 for clarity, kept reference to the original commit by @G-Ray over there

**Pull request closed without merging**
