### PR TITLE
Add BitCore (BTX) support

### PR DESCRIPTION
**Pull request by dalijolijo**
Added BitCore (BTX) support.

Homepage : [bitcore.cc](https://bitcore.cc)
Sources on Github : [https://github.com/LIMXTEC/BitCore](https://github.com/LIMXTEC/BitCore)
Insight : [https://insight.bitcore.cc](https://insight.bitcore.cc)
CMC : [https://coinmarketcap.com/currencies/bitcore](https://coinmarketcap.com/currencies/bitcore)
slip0044 index : 160

### CODE REVIEW

**Comment by dalijolijo** [comment]
See: https://github.com/LedgerHQ/ledger-app-btc/pull/72

**Comment by dalijolijo** [comment]
@gre conflicts in https://github.com/LedgerHQ/ledger-app-btc/pull/72 are resolved now

**Comment by dalijolijo** [comment]
@gre rebase done

**Comment by gre** [comment]
@dalijolijo could you fix the conflict? thanks

**Comment by dalijolijo** [comment]
@gre conflicts resolved

**Comment by gre** [comment]
thanks!

**Pull request merged**
