### PR TITLE
Add LBC support

### PR DESCRIPTION
**Pull request by Nageki**
The .svg logo needs to be made by the design team.

### CODE REVIEW

**Comment by tzarebczan** [comment]
Hey Ledger Team - my name is Tom and I'm from the LBRY team. Please let me know if you have any questions about this and how we can support an expedited process to get this integrated!

**Comment by gre** [comment]
for now we are not accepting PR adding coins, in a near future we should document the way to add new coins to our ecosystem. We'll update our Readme with the process when ready.

**Comment by kodxana** [comment]
@gre Any updates?

**Comment by gre** [comment]
the process is to first have an app delivered on our app store (the list of apps that you find in Manager).
only then, we can start adding cryptocurrencies to the frontend libs and apps.

**Comment by kodxana** [comment]
@gre can you contact me on dev slack? My username Madiator2011

**Pull request closed without merging**
