### PR TITLE
renaming ripple to xrp

### PR DESCRIPTION
**Pull request by amougel**

### CODE REVIEW

**Comment by gre** [comment]
we also need to change the icon , in the SVG files. do we have it? 🤔

**Comment by amougel** [comment]
Yes indeed. We have it

**Comment by gre** [comment]
@amougel we need to commit it here too? in folder https://github.com/LedgerHQ/ledger-live-common/tree/master/src/data/icons/svg and the other folder should sync to it

**Comment by khalilbenihoud** [comment]
Added the new XRP icon (following this: https://xrpsymbol.github.io/) to our library in Zeplin!

**Comment by gre** [comment]
make sure to not merge until we are ready everywhere (e.g. manager)

**Comment by gre** [comment]
there is a weird conflict because i added many coins so i'm going to edit in-place

**Pull request closed without merging**
