### PR TITLE
Add BitSend (BSD) support

### PR DESCRIPTION
**Pull request by dalijolijo**
Added BitSend (BSD) support.

Homepage : https://bitsend.info
Sources on Github : https://github.com/LIMXTEC/BitSend
Explorer : https://chainz.cryptoid.info/bsd
CMC : https://coinmarketcap.com/currencies/bitsend
slip0044 index : 91

### CODE REVIEW

**Comment by gre** [comment]
@dalijolijo usually it is the same as the main color of the Manager app icon.

**Comment by dalijolijo** [comment]
Is a change necessary on my part?

**Comment by gre** [comment]
we are not merging things in live-common if there is not first an Ledger app implemented on the ledger device, validated by the firmware team & delivered on the Ledger Manager app store.

We have not yet written a full documentation the overall process of supporting a new coin but we plan to do it soon.

In the meantime, there is this documentation for the process of writing a ledger app: https://ledger.readthedocs.io/en/latest/additional/publishing_an_app.html

**Comment by dalijolijo** [comment]
@gre Do you mean ledger app like blue-app-btc ( https://github.com/LedgerHQ/blue-app-btc ) ?

**Comment by gre** [comment]
not necessarily. they are both exclusive, don't depend from each other, so they technically can both happen at same time.

There are however a few reason why you want this to happen at the end:

- it makes more sense to have apps shipped to app store first because the fields like `ledgerExplorerId` and `managerAppName` kinda will depend on it.
- live-common reflects exactly what coins is in Manager and don't have coins that could never happen to be shipped (or will but in a long period of time). would be easier to maintain without.
- if we make changes in live-common in the future (which has happen frequently if you look at history of cryptocurrencies.js) it is easier for you that you don't have to keep your pending PR up to date. if these are shipped at the end, you can do it all in one go.

**Comment by dalijolijo** [comment]
@gre rebase done. 
Which color (defined color results in an error) should I use?

**Comment by gre** [comment]
@dalijolijo logo must be mono color (i can see in our SVG there are 2 styles defined). You might want to rewrite yourself the SVG because maybe our converter tool won't support what you have exported (e.g. I doubt about the `<style>`). 
ideally svg would contain the minimal code (see other icons)

the color that must be defined is `currentColor` ([it's a CSS' variable](https://css-tricks.com/currentcolor/)) and will get replaced by our converter.

for instance, this is the Bitcoin icon: https://raw.githubusercontent.com/LedgerHQ/ledger-live-common/master/src/data/icons/svg/bitcoin.svg

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="16" viewBox="0 0 16 16">
  <path fill="currentColor" d="M7.62 0h1.7v3.058h-1.7V0zm1.7 0v3.058h-1.7V0h1.7zM7.813 12.942h1.7V16h-1.7v-3.058zm1.7 0V16h-1.7v-3.058h1.7zM4.406 0h1.7v3.058h-1.7V0zm1.7 0v3.058h-1.7V0h1.7zM4.6 12.942h1.7V16H4.6v-3.058zm1.7 0V16H4.6v-3.058h1.7zM2.666 8.813V1.95h.85l6.139.002c1.807.11 3.212 1.566 3.118 3.254l-.002.279c.111 1.744-1.298 3.217-3.168 3.328H2.666zm.85 0l.85-.85v4.32h5.608c.95-.025 1.676-.727 1.659-1.557v-.37c.019-.814-.707-1.518-1.637-1.543h-6.48zm7.557-3.275l.001-.378c.042-.77-.62-1.457-1.471-1.51H4.366v3.463h5.205c.899-.063 1.552-.753 1.502-1.575zM4.366 7.113l5.186.002.467-.002c1.86.05 3.355 1.5 3.314 3.262v.334c.036 1.779-1.458 3.224-3.337 3.273h-7.33V7.113h1.7zm0 0v.85l-.85-.85h.85z"/>
</svg>
```

**Pull request merged**
