### PR TITLE
Add logo for SSV token

### PR DESCRIPTION
**Pull request by BenAffleck**
## Context (issues, jira)

SSV Token support shipped with version v2.35.0 of the Ledger Live App according to [this discussion](https://github.com/LedgerHQ/ledger-live-desktop/discussions/4312).

## Description / Usage

This PR adds the SSV token logo.

## Expectations

- [x] **Test coverage: The changes of this PR are covered by test.** Unit test were added with mocks when depending on a backend/device.
- [X] **No impact: The changes of this PR have ZERO impact on the userland.** Meaning, we can use these changes without modifying LLD/LLM at all. It will be a "noop" and the maintainers will be able to bump it without changing anything.

### CODE REVIEW

**Comment by BenAffleck** [comment]
@gre Thanks for labeling the case. Who will do the review, and when will it happen? Thanks.

**Comment by BenAffleck** [comment]
@gre Any update? Thx.

**Review by gre — APPROVED** [review]

**Comment by gre** [comment]
@LFBarreto can you confirm this one is good? thanks.

**Review by LFBarreto — APPROVED** [review]

**Comment by BenAffleck** [comment]
@LFBarreto @gre 
Thanks for the approval. One of the build tests failed, but I assume it is unrelated to my PR. 
Please have a look and merge. Thanks.

**Comment by BenAffleck** [comment]
Hello @gre,
Could you please merge now? The process is somewhat unclear to me. Let me know if there is something else I have to do. Thx.

**Comment by BenAffleck** [comment]
Hello @LFBarreto @gre, happy New Year to everyone! 
Is anybody active on this issue? It takes a surprisingly long time to close such a simple PR. Is there anything I can do to speed things up?

**Comment by BenAffleck** [comment]
Hello @gre @LFBarreto, how are you guys doing?
I've received the latest ledger-live update today. Unfortunately, the Icon doesn't show up. Since it isn't showing the generic token icon either, I assume the PR wasn't correct. I have no idea how to fix this. Could you please route me in the right direction? 

Screenshot taken from Ledger Live **2.37.1**:
image
image
image

**Comment by BenAffleck** [comment]
Hello @gre @LFBarreto, how are you guys doing? The problem still exists, even with Ledger Live 2.37.2.
Sorry to bother you, but I need advice. What's wrong with the logo? Please have a look. Thanks.

**Comment by BenAffleck** [comment]
Hello @LFBarreto @gre,
I'm a bit lost here. I don't understand if the problem was solved with #1700 or not? I just downloaded the latest release, but the icon doesn't appear. Can you please shed some light on it, so we can finally unblock it? Thank you.

**Comment by BenAffleck** [comment]
Hello @LFBarreto @gre, please, I need your advice. The logo is still now showing in the latest version. Please let me know what to do next.

**Pull request merged**
