### PR TITLE
add eip-681

### PR DESCRIPTION
**Pull request by machard**
So,
I am not sure if this is full support.
Do we want full support ?
Also I am not sure where to test this ?
https://ledgerhq.atlassian.net/browse/LL-4000

### CODE REVIEW

**Review by gre — CHANGES_REQUESTED** [review]
Check again but I think it is not accepting wei value

**Comment by machard** [comment]
"The amount is specified in value parameter, in the atomic unit (i.e. Wei). The use of scientific notation is strongly encouraged. For example, requesting 2.014 ETH to address 0xfb6916095ca1df60bb79Ce92ce3ea74c37c5d359 would look as follows: ethereum:0xfb6916095ca1df60bb79Ce92ce3ea74c37c5d359?value=2.014e18"
Indeed it seems you're right, no need to do the multiplication

**Comment by gre** [comment]
Can you add tests to cover the different syntaxes? Thanks

**Review by gre — DISMISSED** [review]
please add tests 👍

**Review by gre — APPROVED** [review]

**Pull request merged**
