### PR TITLE
Filecoin fixes

### PR DESCRIPTION
**Pull request by emmanuelm41**
## Context (issues, jira)

These changes are necessary in order to fix some issues on ledger-live-desktop. The PR related to these changes is https://github.com/LedgerHQ/ledger-live-desktop/pull/4589.

## Description / Usage

We have changed the way tx to broadcast is generated, as well as fields the app should show the user for visual confirmation on signing process.

## Expectations

- [ ] **Test coverage: The changes of this PR are covered by test.** Unit test were added with mocks when depending on a backend/device.
- [ ] **No impact: The changes of this PR have ZERO impact on the userland.** Meaning, we can use these changes without modifying LLD/LLM at all. It will be a "noop" and the maintainers will be able to bump it without changing anything.

### CODE REVIEW

**Review by gre — CHANGES_REQUESTED** [review]
Thanks @emmanuelm41 , there are some lint issue on this PR.

Do you know if this would fix the bot issues too? The bot haven't successfully run the tests yet, it fails with a HTTP 5xx apparently (I didn't dig the details) https://github.com/LedgerHQ/ledger-live-common/commit/5fa6a917da4a4789d757ae67eb0679f54ce6cd52#commitcomment-67610578

Cheers

**Comment by emmanuelm41** [comment]
Thanks @gre! Lint issues were fixed.

I am checking bot thing. I am not sure what is happening. On dev we are pointing to a dev node we have. If the bot tries to get addresses with coins on it, it would be difficult for it. I have to fund them first. Let me check what is happening.

**Comment by emmanuelm41** [comment]
@gre the bot is working now... is that correct? --> [results](https://github.com/LedgerHQ/ledger-live-common/runs/5374912452?check_suite_focus=true)

**Comment by gre** [comment]
@emmanuelm41 the "bot" github actions is always passing on the CI. the results are visible on the commit comment where it runs and if it have funds for the coin.

at this stage, from one run to another we seem to experience some 5xx issue. but on the time it "runs" it seems like it doesn't have funds yet, so i'll ask my team to feed some funds too.

**Comment by emmanuelm41** [comment]
Filecoin endpoint points to a local devnet node, so you won't be able to feed some funds to the account. I will do it!

**Review by gre — APPROVED** [review]

**Pull request merged**
