### PR TITLE
LL to correctly uses Vertcoin coinType=28 for new accounts

### PR DESCRIPTION
**Pull request by gre**
- the previous coinType=128 is a mistake and it will now appear as "legacy" in LL
- user will have to clear cache before scanning again Vertcoin accounts otherwise he will see the account appearing twice (because we don't yet sync again the config in libcore wallet)

@Arnaud97234 to test this, you can use the `tool`

### CODE REVIEW

**Comment by meriadec** [comment]
Damned! This error:

```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found
(required by /home/circleci/live-common/tool/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.so)
```

@teams2ua we faced the pb yesterday on your Ubuntu, if I remember correctly you fixed by installing a previous libcore version?

**Comment by teams2ua** [comment]
Yeap, I checkouted taged version 

-----Исходное сообщение-----
От: "Meriadec Pillet" <notifications@github.com>
Отправлено: ‎25.‎04.‎2019 10:01
Кому: "LedgerHQ/ledger-live-common" <ledger-live-common@noreply.github.com>
Копия: "teams2ua" <teams2ua@gmail.com>; "Mention" <mention@noreply.github.com>
Тема: Re: [LedgerHQ/ledger-live-common] LL to correctly uses VertcoincoinType=28 for new accounts (#210)

Damned! This error:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found
(required by /home/circleci/live-common/tool/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.so)
@teams2ua we faced the pb yesterday on your Ubuntu, if I remember correctly you fixed by installing a previous libcore version?

**Comment by gre** [comment]
@meriadec this was already reported LLC-216 and is independent from this PR. Hopefully we can still see if the CI succeed and mac for running the tests.

**Comment by teams2ua** [comment]
The problem with glibc should be fixed if on your CI update compiler to gcc 7, the easy way to do this is to go to Debian buster, default gcc there should be fine.

-----Исходное сообщение-----
От: "Gaëtan Renaudeau" <notifications@github.com>
Отправлено: ‎25.‎04.‎2019 10:10
Кому: "LedgerHQ/ledger-live-common" <ledger-live-common@noreply.github.com>
Копия: "teams2ua" <teams2ua@gmail.com>; "Mention" <mention@noreply.github.com>
Тема: Re: [LedgerHQ/ledger-live-common] LL to correctly uses VertcoincoinType=28 for new accounts (#210)

@meriadec this was already reported LLC-216 and is independent from this PR. Hopefully we can still see if the CI succeed and mac for running the tests.

**Pull request merged**
