### PR TITLE
Update XRPL node (s2.ripple.com » xrpl.ws)

### PR DESCRIPTION
**Pull request by WietseWind**
The Ledger software uses the Ripple provided `s2.ripple.com` full history node. **This node is not for production use.**

Due to an expired root certificate, [Twitter is currently filling](https://twitter.com/search?q=certificate%20xrp&src=typed_query&f=live) up with messages from users complaining about a certificate warning.
https://twitter.com/WietseWind/status/1267019432196558850

XRP ledger community developers provide and maintain global, load balanced, geo redundant full history nodes (clustered) with live failover as well, at https://xrpl.ws/ (wss://xrpl.ws)

Many community apps already rely on xrpl.ws.

### CODE REVIEW

**Comment by nbougalis** [comment]
I very much approve of using the **xrpl.ws** load-balancer as the primary server.

**Comment by RareData** [comment]
Please setup your own node @ledgerlive

**Comment by WietseWind** [comment]
> Please setup your own node @ledgerlive
> https://xrpl.org/manage-the-rippled-server.html

That would be even better. If you need help with that: this is me offering.

**Comment by SASchofield** [comment]
Preferable for Ledger to operate their own node but as a great alternative and for the time being - The community would recommend xrpl.ws as a far better option than the s2.ripple.com

Also, why was the option for users to choose their own XRPL servers removed from the Ledger Live client?

**Comment by gre** [comment]
Thanks for your PR, this is definitely a better option for now and we'll discuss internally about the other feedbacks. 🙂

**Pull request merged**
