### PR TITLE
Update asa.js

### PR DESCRIPTION
**Pull request by jtmarkley1**
Updating with new assets such as USDC

### CODE REVIEW

**Review by FabriceDautriat — COMMENTED** [review]
LGTM (need to confirm the ASA details by fetching information from node)

**Review by gre — APPROVED** [review]

**Comment by FabriceDautriat** [comment]
Version 1.2.9 of the Algorand app is mandatory, please make sure to update 
See https://github.com/LedgerHQ/ledger-live-common/pull/878

**Comment by gre** [comment]
Thanks for the PR,

as the device also includes the tokens data and old version would be incompatible with this new list we also need to make sure this is used with the latest app.

to do so, in src/apps/support.js, we have a appVersionsRequired map that will express what required version is needed, can you update it to `>= 1.2.9` please?

thanks

**Comment by gre** [comment]
oh i didn't see it was another PR. ok we can merge both.

**Pull request merged**
