### PR TITLE
Ledger Common Verge integration 

### PR DESCRIPTION
**Pull request by marpme**
Basic Verge integration for supporting it inside the companion app. 

other PR references are: https://github.com/LedgerHQ/ledger-app-btc/pull/43
If there's anything left to be changed, please just drop me a comment.

### CODE REVIEW

**Comment by gre** [comment]
ping me when there is an app on manager available. thanks.

**Comment by marpme** [comment]
Do you mean a further integrating of our system into https://github.com/LedgerHQ/ledgerjs? 
Or what do you mean by?

>  ...when there is an app on manager available.

**Comment by RAMBORG** [comment]
?

**Comment by Kryptoxic** [comment]
> Do you mean a further integrating of our system into https://github.com/LedgerHQ/ledgerjs?
> Or what do you mean by?
> 
> > ...when there is an app on manager available.

I think he meant to say mention him again when the actual app is released for the Nano S before the implementation into Ledger Live

**Pull request closed without merging**
