### PR TITLE
Added NavCoin Support for ledger-live-common

### PR DESCRIPTION
**Pull request by mxaddict**
Added NavCoin Support for ledger-live-common libs

Can anyone point me to where to go next in my journey to add NavCoin to Ledger-Live-Desktop app?

### CODE REVIEW

**Comment by mxaddict** [comment]
@gre I will be adding the LOG/SVG shortly

As for this END Point: https://countervalues.api.live.ledger.com/exchanges/NAV/BTC

How do I go about getting this approved?

**Comment by gre** [comment]
Countervalues API uses this same library so there is nothing to do.

**Comment by mxaddict** [comment]
@gre after adding the new coin in this lib, where else do I need to work on to get the coin onto ledger live apps?

**Comment by gre** [comment]
So the first thing to have an cryptocurrency supported is to make a Ledger app and having it land in Manager, only then we can merge this PR. i'll close it for now and we can still re-open when it's time :) 

@mxaddict  For now, you can discuss with us in our dev slack, are you in Ledger Devs slack? i can invite you

**Comment by mxaddict** [comment]
@gre I've created a PR for the BOLOS app to be added to the ledger manager already.

https://github.com/LedgerHQ/ledger-app-btc/pull/115

Yes, please invite me to the dev slack. 

I already filed the form for dev slack, but have not been added yet.

**Pull request closed without merging**
