### PR TITLE
Add deviceTransactionConfig.ts for cryptoorg

### PR DESCRIPTION
**Pull request by thomas-nguy**
## Context (issues, jira)

Add missing deviceTransactionConfig.ts file

## Expectations

- [ ] **Test coverage: The changes of this PR are covered by test.** Unit test were added with mocks when depending on a backend/device.
- [ ] **No impact: The changes of this PR have ZERO impact on the userland.** Meaning, we can use these changes without modifying LLD/LLM at all. It will be a "noop" and the maintainers will be able to bump it without changing anything.

### CODE REVIEW

**Review by gre — CHANGES_REQUESTED** [review]
lint issues. thanks

**Comment by thomas-nguy** [comment]
fixed

**Comment by gre** [comment]
@thomas-nguy can you run yarn and commit all the files? CI detects a change in generated. Thanks

**Comment by thomas-nguy** [comment]
yes, added

**Pull request merged**
