### PR TITLE
(AppHW): fix loading after connect app polling

### PR DESCRIPTION
**Pull request by LFBarreto**
After a successfull app connect device becomes unresponsive we now show a loading between this state and getting the derivation ﻿for the accounts.

### CODE REVIEW

**Comment by gre** [comment]
(i'm setting this on hodl until next sprint, to focus our QA on the essential parts)

**Comment by gre** [comment]
@LFBarreto what do you think is the status of this PR? should this land on master, does it require some extensive QA?

**Comment by LFBarreto** [comment]
> @LFBarreto what do you think is the status of this PR? should this land on master, does it require some extensive QA?

I think we need to QA this and check if that doesn't break anything. I'm pretty sure the impact is minor but helps on the UX of the app flow

**Comment by gre** [comment]
to be revisited.

**Pull request closed without merging**
